import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "sonner";
import Providers from "./providers";
import { Suspense } from "react";
import { Geist, Geist_Mono } from "next/font/google";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// const myFont = localFont({
//   src: "./Acumin.woff2",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/site-logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`min-h-screen min-w-full
         antialiased`}
        style={{ fontFamily: "Acumin, sans-serif" }}
      >
        <Providers>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </Providers>
      </body>
    </html>
  );
}

function Loading() {
  return (
    <div className="fixed inset-0 z-50 flex items-center bg-back justify-center bg-opacity-70">
      <div className="w-12 h-12 border-4 border-blue-200 border-t-transparent rounded-full animate-spin"></div>
    </div>
  );
}
